openapi: 3.0.0
info:
  version: 1.0.0
  title: Back End Demonstration API
  description: A simple blog API.
  contact:
    name: Lin Wai Kai
    email: 247026150@stu.vtc.edu.hk
  license:
    name: Apache 2.0
    url: 'https://www.apache.org/licenses/LICENSE-2.0.html'
servers:
  - url: 'https://localhost:10888/api/v1'
    description: Development server
tags:
  - name: Users
    description: API endpoints for user management.
  - name: Articles
    description: Access and perform CRUD operations on blog entries.
paths:
  /articles:
    get:
      tags:
        - Articles
      description:
        Get All articles from database
    post:
      tags:
        - Articles
      description:
        Update article by ID.
      requestBody:
        description: All new articles data.
        required: true
        content:
          application/json:
            schema:
              $ref: ./article.json#/definitions/articles
  /articles/{id}:
    parameters:
      - in: path
        name: id
        schema:
          type: integer
        required: true
        description: Numeric id of the article (not less than 0)
    get:
      tags:
        - Articles
      description:
        Get article by id.
      responses:
        '200':
          description: View of an article record.
        '404':
          description: Article was not found in the DB.
    put:
      tags:
        - Articles
      description:
        Update article by ID.
      responses:
        '200':
          description: Update confirmation and link to record.
        '404':
          description: Article was not found in the DB. 
    delete:
      tags:
        - Articles
      description:
        Delete article by ID.
      responses:
        '200':
          description: Delete confirmation.
        '404':
          description: User was not found in the DB.

